### ISSUE TITLE
希望 GitHub代码浏览树 支持 黑暗模式 皮肤

### ISSUE THREAD

**Issue by charygao** [lijian17/54Helper#1]
希望 GitHub代码浏览树 支持 黑暗模式 皮肤 以配合 “DARK READER” 插件 一起使用，方便夜间的代码浏览。

**Comment by lijian17** [comment]
### v4.3.0新增GitHub代码浏览树主题模式
1、GitHub代码浏览树设置界面可以勾选Dark主题模式皮肤，以配合 “DARK READER” 插件 一起使用，方便夜间的代码浏览。
